* Options                                                  :noexport:ARCHIVE:
#+title: README
#+options: toc:nil num:nil author:nil creator:nil date:nil timestamp:nil
#+html_head: <link rel="stylesheet" type="text/css" href="css/simple.css" />
#+html_head: <style> #content{max-width:1200px;}</style>
#+html_head_extra: <style type="text/css">
#+html_head_extra:  pre.src-powershell{ background:#191970;color:#daa520;}
#+html_head_extra:  pre.src-shell{ color:black;}
#+html_head_extra:  pre.src:hover:before { display: none; }
#+html_head_extra:  pre.example{ background:#e3e3e3; color:black; }
#+html_head_extra: </style>
#+startup: indent show2levels



* Simple bootstrap scripts for new installations.
The intention for these scripts are to setup a new system in a standardized way with minimum user intervention.
But a lot of things might need customization anyway. Works on my machine...

** Linux
[[file:boot.sh][boot.sh]]

*** Install
#+begin_src shell
curl https://boot.charlottendal.net/boot.sh|bash
#+end_src

** Windows
*** Install Winget
[[file:WinGet.ps1][WinGet.ps1]]

#+name: Install-WinGet
#+begin_src powershell
iwr "https://boot.charlottendal.net/WinGet.ps1" -OutFile WinGet.ps1
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force
.\WinGet.ps1
#+end_src

*** Boot script
[[file:boot.ps1][boot.ps1]]

*** Install
In powershell as admin.
#+begin_src powershell
iwr "https://boot.charlottendal.net/boot.ps1" -OutFile boot.ps1
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force
.\boot.ps1
#+end_src

* Install basic PowerShell profile
Install a PowerShell profile on systems that should have a minimum of third party software installed, like servers.
This will most likely only work on the =Desktop= version of PowerShell on Windows, ie 4.0 and up.

#+begin_src powershell
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls11 -bor [System.Net.SecurityProtocolType]::Tls12
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force
New-Item $Profile.CurrentUserAllHosts -Force
iwr "https://boot.charlottendal.net/profile.ps1" -OutFile $Profile
. $profile
Set-PSConsole

#+end_src

[[https://github.com/sdaaish/boot][GitHub src]]

** Testing
Put certificates if needed in the *Build* folder and do a =gen-sandboxconf.ps1= in that folder.
Start with =.\boot-sandbox.wsb=

This will start the Windows sandbox and run the installation.

